{{- if .Values.diffBQTable.create }}
{{- $schemaImage := printf "%s:%s" .Values.diffBQTable.schemaImageName (default "latest" .Values.diffBQTable.schemaImageVersion ) }}
{{- $alwaysPull := not .Values.diffBQTable.schemaImageVersion }}
{{- $exportTemplate := default (printf "%s-export" .Values.diffBQTable.name) .Values.exportBQTable.name }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.diffBQTable.name }}
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: old-ids-output-prefix
          - name: new-rows-output-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
      dag:
        tasks:
          # Build a join table containing both IDs to delete and new rows to append.
          - name: join-staging-to-existing
            template: join-staging-to-existing
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: input-prefix
                  value: '{{ "{{inputs.parameters.input-prefix}}" }}'
                - name: staging-bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: staging-bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: jade-bq-project
                  value: '{{ "{{inputs.parameters.jade-bq-project}}" }}'
                - name: jade-bq-dataset
                  value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'

          # Export the IDs of existing rows that should be soft-deleted.
          - name: query-ids-to-delete
            dependencies: [join-staging-to-existing]
            template: query-ids-to-delete
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: join-table-name
                  value: '{{ "{{tasks.join-staging-to-existing.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
          - name: export-deletes
            dependencies: [query-ids-to-delete]
            templateRef:
              name: {{ $exportTemplate }}
              template: main
            arguments:
              parameters:
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: bq-table
                  value: '{{ "{{tasks.query-ids-to-delete.outputs.result}}" }}'
                - name: output-format
                  value: CSV
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: gcs-prefix
                  value: '{{ "{{inputs.parameters.old-ids-output-prefix}}" }}'

          # Export the values of new rows that should be appended.
          - name: query-rows-to-append
            dependencies: [join-staging-to-existing]
            template: query-rows-to-append
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: join-table-name
                  value: '{{ "{{tasks.join-staging-to-existing.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
          - name: export-appends
            dependencies: [query-rows-to-append]
            templateRef:
              name: {{ $exportTemplate }}
              template: main
            arguments:
              parameters:
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: bq-table
                  value: '{{ "{{tasks.query-rows-to-append.outputs.result}}" }}'
                - name: output-format
                  value: NEWLINE_DELIMITED_JSON
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: gcs-prefix
                  value: '{{ "{{inputs.parameters.new-rows-output-prefix}}" }}'
      outputs:
        parameters:
          - name: ids-to-delete-count
            valueFrom:
              parameter: '{{ "{{tasks.export-deletes.outputs.parameters.row-count}}" }}'
          - name: rows-to-append-count
            valueFrom:
              parameter: '{{ "{{tasks.export-appends.outputs.parameters.row-count}}" }}'
          - name: join-table-name
            valueFrom:
              parameter: '{{ "{{tasks.join-staging-to-existing.outputs.result}}" }}'
      {{- if .generateMetrics }}
      metrics:
        prometheus:
          {{- include "argo.collect-execution-metrics" . | indent 10 }}
          - name: rows_to_delete
            help: 'Number of rows to be deleted'
            labels:
              - key: table-name
              - value: '{{ "{{inputs.parameters.table-name}}" }}'
            when: '{{ "{{status}}" }} == Succeeded'
            gauge:
              value: '{{ "{{outputs.parameters.ids-to-delete-count}}" }}'
          - name: rows_to_append
            help: 'Number of rows to be added'
            labels:
              - key: table-name
              - value: '{{ "{{inputs.parameters.table-name}}" }}'
            when: '{{ "{{status}}" }} == Succeeded'
            gauge:
              value: '{{ "{{outputs.parameters.rows-to-append-count}}" }}'
      {{- end }}

    - name: join-staging-to-existing
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
      script:
        image: {{ $schemaImage }}
        {{- if $alwaysPull }}
        imagePullPolicy: Always
        {{- end }}
        env:
          - name: STAGING_PROJECT
            value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
          - name: STAGING_DATASET
            value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
          - name: JADE_PROJECT
            value: '{{ "{{inputs.parameters.jade-bq-project}}" }}'
          - name: JADE_DATASET
            value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.table-name}}" }}'
          - name: GCS_PREFIX
            value: '{{ "gs://{{inputs.parameters.gcs-bucket}}/{{inputs.parameters.input-prefix}}" }}'
        command: [bash]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/diff-bq-table.sh") | indent 10 }}

    - name: query-ids-to-delete
      inputs:
        parameters:
          - name: table-name
          - name: join-table-name
          - name: bq-project
          - name: bq-dataset
      script:
        image: {{ $schemaImage }}
        {{- if $alwaysPull }}
        imagePullPolicy: Always
        {{- end }}
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.bq-dataset}}" }}'
          - name: INPUT_TABLE
            value: '{{ "{{inputs.parameters.join-table-name}}" }}'
          - name: OUTPUT_PREFIX
            value: '{{ "{{inputs.parameters.table-name}}" }}'
        command: [bash]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/query-non-null-row-ids.sh") | indent 10 }}

    - name: query-rows-to-append
      inputs:
        parameters:
          - name: table-name
          - name: join-table-name
          - name: bq-project
          - name: bq-dataset
      script:
        image: {{ $schemaImage }}
        {{- if $alwaysPull }}
        imagePullPolicy: Always
        {{- end }}
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.bq-dataset}}" }}'
          - name: INPUT_TABLE
            value: '{{ "{{inputs.parameters.join-table-name}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.table-name}}" }}'
        command: [bash]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/query-non-null-rows.sh") | indent 10 }}
{{- end }}
