{{- if .Values.lookupFileId.create }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.lookupFileId.name }}
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: url
          - name: dataset-id
          - name: virtual-path
          - name: sa-secret
          - name: sa-secret-key
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: '{{ "{{inputs.parameters.sa-secret}}" }}'
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-auth-req-py:1.0.1
        volumeMounts:
          - name: sa-secret-volume
            mountPath: /secret
        env:
          - name: API_URL
            value: '{{ "{{inputs.parameters.api-url}}" }}'
          - name: DATASET_ID
            value: '{{ "{{inputs.parameters.dataset-id}}" }}'
          - name: TARGET_PATH
            value: '{{ "{{inputs.parameters.virtual-path}}" }}'
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: '{{ "/secret/{{inputs.parameters.sa-secret-key}}" }}'
        command: [python]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/lookup-file-id.py") | indent 10 }}
{{- end }}
