apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: poll-ingest-job
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: api-url
          - name: job-id
          - name: timeout
          - name: sa-secret
          - name: sa-secret-key
          - name: sa-secret-volume
          - name: volume-mount-path
      volumes:
        - name: '{{ "{{inputs.parameters.secret-volume}}" }}'
          secret:
            secretName: '{{ "{{inputs.parameters.sa-secret}}" }}'
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-auth-req-py:1.0.1
        env:
          - name: API_URL
            value: '{{ "{{inputs.parameters.api-url}}" }}'
          - name: JOB_ID
            value: '{{ "{{inputs.parameters.job-id}}" }}'
          - name: TIMEOUT
            value: '{{ "{{inputs.parameters.timeout}}" }}'
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: '{{ printf "%s/{{inputs.parameters.sa-secret-key}}" $mountPath }}'
        volumeMounts:
          - name: '{{ "{{inputs.parameters.secret-volume}}" }}'
            mountPath: '{{ $mountPath }}'
        command: [python]
        source: |
          {{- include "argo.render-lines" (.Files.Lines "scripts/poll-ingest-job.py") | indent 10 }}