apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-storage
        - name: config
          emptyDir: {}
      initContainers:
        # Set up UID/GID on data storage before creating
        # the corresponding user.
        - name: set-permissions
          image: alpine
          volumeMounts:
            - name: data
              mountPath: /data
          command: ["sh", "-c"]
          args: ["chown -R 1003:1005 /data"]
        # Register a virtual user, rooted in the data volume.
        - name: add-user
          image: crazymax/pure-ftpd:1.0.49
          volumeMounts:
            - name: config
              mountPath: /etc/pureftpd
          env:
            - name: PURE_PASSWDFILE
              value: /etc/pureftpd/pureftpd.passwd
            - name: PURE_DBFILE
              value: /etc/pureftpd/pureftpd.pdb
            {{- with .Values.user.passwordSecret }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end}}
          command: ["sh", "-c"]
          args:
            - |-
              echo -e "${PASSWORD}\n${PASSWORD}" | \
              pure-pw useradd {{ .Values.user.username }} \
                -u 1003 -g 1005 -d /home/{{ .Values.user.username }} -m
      containers:
        - name: ftp-server
          image: crazymax/pure-ftpd:1.0.49
          volumeMounts:
            - name: data
              mountPath: /home/{{ .Values.user.username }}
            - name: config
              mountPath: /data
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PASSIVE_IP
              value: {{ .Release.Name }}.$(K8S_NAMESPACE)
            {{- with .Values.connection.passiveMode }}
            - name: PASSIVE_PORT_RANGE
              value: {{ .minPort }}:{{ .maxPort }}
          ports:
            - name: command-port
              containerPort: 2100
              protocol: TCP
            {{- range $i, $p := (untilStep (int .minPort) (int (add .maxPort 1)) 1) }}
            - name: passive-port-{{$i}}
              containerPort: {{$p}}
              protocol: TCP
            {{- end}}
          {{- end}}
