{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-use-psp-binding
  labels:
    {{- include "pure-ftpd.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pure-ftpd.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-use-psp-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
