{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-use-psp-role
  labels:
    {{- include "pure-ftpd.labels" . | nindent 4 }}
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['{{ .Release.Name }}-pod-running-policy']
{{- end }}
