{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pure-ftpd.serviceAccountName" . }}
  labels:
    {{- include "pure-ftpd.labels" . | nindent 4 }}
{{- end }}
