apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "pure-ftpd.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pure-ftpd.selectorLabels" . | nindent 4 }}
  ports:
    - name: command-port
      port: {{ .Values.connection.port }}
      targetPort: command-port
      protocol: TCP
    {{- with .Values.connection.passiveMode }}
    {{- range $i, $p := (untilStep (int .minPort) (int (add .maxPort 1)) 1) }}
    - name: passive-port-{{$i}}
      port: {{$p}}
      targetPort: passive-port-{{$i}}
      protocol: TCP
    {{- end}}
    {{- end}}
