#!/usr/bin/env bash
set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname ${0}) >/dev/null 2>&1 && pwd)
declare -r REPO_ROOT=$(cd $(dirname ${SCRIPT_DIR}) >/dev/null 2>&1 && pwd)
declare -r TEMP_DIR=${REPO_ROOT}/deploy

function lookup_latest_tag () {
  git fetch --tags &> /dev/null

  if ! git describe --tags --abbrev=0 2> /dev/null; then
    git rev-list --max-parents=0 --first-parent HEAD
  fi
}

function lookup_changed_charts () {
  local -r commit=$1
  local -r changed_files=$(git diff --find-renames --name-only ${commit} -- charts)
  local -ra changed_prefixes=($(echo ${changed_files} | cut -d / -f 1,2 | uniq))

  for prefix in ${changed_prefixes[@]}; do
    if [[ -d ${prefix} ]]; then
      if [[ -f ${prefix}/Chart.yaml ]]; then
        echo ${prefix}
      fi
    fi
  done
}

function main () {
  trap "cd $(pwd)" EXIT
  cd ${REPO_ROOT}

  1>&2 echo Looking up latest tag...
  local -r latest_tag=$(lookup_latest_tag)

  1>&2 echo Discovering charts changed since "'${latest_tag}'"...
  local -ra changed_charts=($(lookup_changed_charts ${latest_tag}))

  if [[ -z "${changed_charts[*]}" ]]; then
    1>&2 echo No changed charts to upload
  else
    1>&2 echo Packaging discovered charts...
    rm -rf ${TEMP_DIR}
    mkdir -p ${TEMP_DIR}
    helm package \
      --destination ${TEMP_DIR} \
      --dependency-update \
      ${changed_charts[@]}

    1>&2 echo Uploading charts...
    cr upload -o broadinstitute -r monster-helm
  fi
}

main
