apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}-account
      containers:
        - name: argo-server
          image: argoproj/argocli:v2.5.1
          args:
            - server
            - --configmap
            - {{ .Release.Name }}-config
            - --auth-mode
            - client
          ports:
            - containerPort: 2746
              name: http
          readinessProbe:
            httpGet:
              port: http
              scheme: HTTP
              path: /
            initialDelaySeconds: 10
            periodSeconds: 20
