apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}-account
      containers:
        - name: argo-server
          image: argoproj/argocli:v2.7.0-rc2
          args:
            - server
            - --configmap
            - {{ .Release.Name }}-config
            - --auth-mode
            - client
            {{- if .Values.debug }}
            - --loglevel
            - debug
            {{- end }}
          {{- if .Values.debug }}
          env:
            - name: UPPERIO_DB_DEBUG
              value: "1"
          {{- end }}
          ports:
            - containerPort: 2746
              name: http
          readinessProbe:
            httpGet:
              port: http
              scheme: HTTP
              path: /
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: http
              scheme: HTTP
              path: /
            initialDelaySeconds: 30
            periodSeconds: 10
