---
{{- $secretName := printf "%s-persistence-user" .Release.Name }}
{{- $secretKey := "username" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  {{ $secretKey }}: {{ .Values.persistence.username | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  artifactRepository: |
    archiveLogs: true
    gcs:
      bucket: {{ .Values.logs.bucket }}
  containerRuntimeExecutor: {{ .Values.executor }}
  {{- if .Values.debug }}
  executor: |
    args: ['--loglevel', 'debug']
  {{- end }}
  persistence: |
    nodeStatusOffLoad: true
    archive: true
    clusterName: {{ .Values.clusterName }}
    {{- with .Values.persistence }}
    postgresql:
      host: {{ .host }}
      port: {{ .port }}
      database: {{ .database }}
      tableName: argo_workflows
      userNameSecret:
        name: {{ $secretName }}
        key: {{ $secretKey }}
      {{- with .password }}
      passwordSecret:
        name: {{ .secretName }}
        key: {{ .secretKey }}
      {{- end }}
    {{- end }}
  {{- with .Values.workflowDefaults }}
  {{- if or .podGarbageCollection.enabled .workflowTTL.enabled }}
  workflowDefaults: |
    {{- if .podGarbageCollection.enabled }}
    podGC:
      strategy: {{ .podGarbageCollection.strategy }}
    {{- end }}
    {{- if .workflowTTL.enabled }}
    ttlStrategy:
      secondsAfterSuccess: {{ .workflowTTL.secondsAfterSuccess }}
      secondsAfterFailure: {{ .workflowTTL.secondsAfterFailure }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.metrics }}
  metricsConfig: |
    disableLegacy: true
    enabled: {{ .enabled }}
    path: {{ .path }}
    port: {{ .port }}
  {{- end }}
