---
{{- $secretName := printf "%s-persistence-user" .Release.Name }}
{{- $secretKey := "username" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  {{ $secretKey }}: {{ .Values.persistence.username | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config: |
    containerRuntimeExecutor: {{ .Values.executor }}
    {{- if .Values.debug }}
    executor:
      args: ['--loglevel', 'debug']
    {{- end }}
    persistence:
      nodeStatusOffLoad: true
      archive: true
      {{- with .Values.persistence }}
      clusterName {{ .clusterId }}
      postgresql:
        host: {{ .host }}
        port: {{ .port }}
        database: {{ .database }}
        tableName: argo_workflows
        userNameSecret:
          name: {{ $secretName }}
          key: {{ $secretKey }}
        {{- with .password }}
        passwordSecret:
          name: {{ .secretName }}
          key: {{ .secretKey }}
        {{- end }}
      {{- end }}
