apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}-account
      containers:
        - name: workflow-controller
          image: argoproj/workflow-controller:v2.7.7
          command: [workflow-controller]
          args:
            - --configmap
            - {{ .Release.Name }}-config
            - --executor-image
            - argoproj/argoexec:v2.7.7
            - --namespaced
            {{- if .Values.debug }}
            - --loglevel
            - debug
            {{- end }}
          {{- if .Values.debug }}
          env:
            - name: UPPERIO_DB_DEBUG
              value: "1"
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
          {{- end }}
