apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}-account
      containers:
        name: workflow-controller
        image: argoproj/workflow-controller:{{ .Chart.AppVersion }}
        command: [workflow-controller]
        args:
          - --configmap
          - {{ .Release.Name }}-config
          - --executor-image
          - argoproj/argoexec:{{ .Chart.AppVersion }}
          - --namespaced
