name: Release new charts
on:
  push:
    branches:
      - master
jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Needed to actually find the last released tag.
      # https://github.com/helm/chart-releaser-action/issues/13
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Validate charts
        run: ./hack/validate-charts
      - uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
