name: Release new charts
on:
  push:
    branches:
      - master
jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.1.2'
      - uses: broadinstitute/setup-chart-releaser@v1
        with:
          version: '1.0.0-beta.1'
      # Needed to actually find the last released tag.
      # https://github.com/helm/chart-releaser-action/issues/13
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - run: ./hack/upload-changed-charts
        env:
          CR_TOKEN: ${{ secrets.ChartReleaserToken }}
