name: PR Validation
on:
  pull_request:
    branches:
      - [ '*' ]
jobs:
  ci:
    strategy:
      fail-fast: false
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate charts
        run: ./hack/validate-charts
      - uses: actions/setup-python@v2
      - name: Run python script tests
        uses: abatilo/actions-poetry@v2.0.0
