name: PR Validation
on:
  pull_request:
    branches:
      - master
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate charts
        run: ./hack/validate-charts
